### ISSUE TITLE
Broken webm file

### ISSUE THREAD

**Issue by murkle** [malikolivier/webmgl#2]
This fork works really well with no changes, thanks!

This fix looks worth adding:
https://github.com/conundrumer/whammy/commit/eba8047f7006c3c683ec2bfe3cd68f797b248871

Original bug report:
https://github.com/antimatter15/whammy/issues/43

**Comment by malikolivier** [comment]
Glad to hear that! I see the issue.

whammy and this fork currently work on Chrome, but does not seem to work on Firefox. 

I will do some check, update the README, and take the fix you pointed at as soon as I got some time! Thanks!

**Comment by murkle** [comment]
Firefox supports webm but not webp (so I think it can't work without major change)
https://caniuse.com/#feat=webp
https://caniuse.com/#feat=webm

Doesn't look like they're going to add **encoding** support for webp either:
https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c123
